services:
  bed-server:
    build: .
    ports:
      - 3000:3000

  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres